# .streamlit/secrets.toml
[connections_oracle]
dialect = "oracle"
host = "61.106.19.***"
port = 33389
database = "CDB1"
username = "DPKMAPP"
password = "***"
encoding = 'UTF-8'

[opai_api_key]
api_key = 'sk-**'